data_ingestion:
  dataset_url: "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"
  dataset_path: "data/raw/iris.csv"

data_preprocessing: 
  test_size: 0.2
  random_state: 42
  train_path: "data/processed/train.csv"
  test_path: "data/processed/test.csv"

train:
  algorithm: "random_forest"
  hyperparameters:
    n_estimators: 100
    max_depth: 5
    random_state: 42
  model_path: "models/model.pkl"
  scaler_path: "models/scaler.pkl" 

evaluate:
  performance_threshold: 0.90
  metrics_path: "metrics/eval_metrics.json"

mlflow:
  experiment_name: "iris_classification"
  tracking_uri: "http://localhost:5000"