apiVersion: v1
kind: ConfigMap
metadata:
  name: streamlit-config
data:
  app.py: |
    import streamlit as st
    import requests
    import pandas as pd
    import plotly.express as px
    import os

    st.set_page_config(page_title="Iris Classifier", page_icon="🌸", layout="wide")
    st.title("🌸 Iris Classification MLOps Demo")

    # Get API URL from environment
    API_BASE = os.getenv("API_BASE", "http://iris-service")

    col1, col2 = st.columns(2)
    
    with col1:
        sepal_length = st.slider("Sepal Length (cm)", 4.0, 8.0, 5.0)
        sepal_width = st.slider("Sepal Width (cm)", 2.0, 5.0, 3.0)
        
    with col2:
        petal_length = st.slider("Petal Length (cm)", 1.0, 7.0, 4.0)
        petal_width = st.slider("Petal Width (cm)", 0.1, 3.0, 1.0)
    
    if st.button("Predict Species", type="primary"):
        payload = {
            "sepal_length": sepal_length,
            "sepal_width": sepal_width,
            "petal_length": petal_length,
            "petal_width": petal_width
        }
        
        try:
            response = requests.post(f"{API_BASE}/predict_single", json=payload, timeout=10)
            if response.status_code == 200:
                st.success(f"🎉 {response.text}")
            else:
                st.error(f"API Error: {response.status_code}")
        except Exception as e:
            st.error(f"Connection error: {str(e)}")

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - name: streamlit
        image: python:3.8-slim
        ports:
        - containerPort: 8501
        command: ["/bin/bash"]
        args:
          - -c
          - |
            pip install streamlit requests pandas plotly
            mkdir -p /app
            echo '$STREAMLIT_APP' > /app/app.py
            streamlit run /app/app.py --server.address 0.0.0.0
        env:
        - name: API_BASE
          value: "http://iris-service"
        - name: STREAMLIT_APP
          valueFrom:
            configMapKeyRef:
              name: streamlit-config
              key: app.py

---
apiVersion: v1
kind: Service
metadata:
  name: streamlit
spec:
  selector:
    app: streamlit
  ports:
  - port: 8501
    targetPort: 8501
  type: LoadBalancer